export enum ProjectsActions {
  FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST",
  FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE",

  PROJECT_EDIT = "PROJECT_EDIT",
  PROJECT_CREATE = "PROJECT_CREATE"
}